# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_gpu_eevee.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dispositivos_eevee(object):
    def setupUi(self, dispositivos_eevee):
        dispositivos_eevee.setObjectName("dispositivos_eevee")
        dispositivos_eevee.setWindowModality(QtCore.Qt.WindowModal)
        dispositivos_eevee.resize(403, 105)
        dispositivos_eevee.setSizeGripEnabled(True)
        dispositivos_eevee.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dispositivos_eevee)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lista = QtWidgets.QComboBox(dispositivos_eevee)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lista.sizePolicy().hasHeightForWidth())
        self.lista.setSizePolicy(sizePolicy)
        self.lista.setMinimumSize(QtCore.QSize(100, 0))
        self.lista.setObjectName("lista")
        self.horizontalLayout.addWidget(self.lista)
        self.btn_encontrar = QtWidgets.QPushButton(dispositivos_eevee)
        self.btn_encontrar.setObjectName("btn_encontrar")
        self.horizontalLayout.addWidget(self.btn_encontrar)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.lbl_dispositivo = QtWidgets.QLabel(dispositivos_eevee)
        self.lbl_dispositivo.setObjectName("lbl_dispositivo")
        self.gridLayout.addWidget(self.lbl_dispositivo, 0, 0, 1, 1)
        self.lbl_path = QtWidgets.QLabel(dispositivos_eevee)
        self.lbl_path.setObjectName("lbl_path")
        self.gridLayout.addWidget(self.lbl_path, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.field_path = QtWidgets.QLineEdit(dispositivos_eevee)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(95)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_path.sizePolicy().hasHeightForWidth())
        self.field_path.setSizePolicy(sizePolicy)
        self.field_path.setObjectName("field_path")
        self.horizontalLayout_2.addWidget(self.field_path)
        self.btn_brwse = QtWidgets.QPushButton(dispositivos_eevee)
        self.btn_brwse.setObjectName("btn_brwse")
        self.horizontalLayout_2.addWidget(self.btn_brwse)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(dispositivos_eevee)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(dispositivos_eevee)
        self.aceptar_cancelar.accepted.connect(dispositivos_eevee.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(dispositivos_eevee.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dispositivos_eevee)

    def retranslateUi(self, dispositivos_eevee):
        _translate = QtCore.QCoreApplication.translate
        dispositivos_eevee.setWindowTitle(_translate("dispositivos_eevee", "Dialog"))
        self.btn_encontrar.setText(_translate("dispositivos_eevee", "Encontrar dispoinbles"))
        self.lbl_dispositivo.setText(_translate("dispositivos_eevee", "Dispositivo:"))
        self.lbl_path.setText(_translate("dispositivos_eevee", "Ruta ejecutable:"))
        self.btn_brwse.setText(_translate("dispositivos_eevee", "Browse"))
