# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'argumentos_extra.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_argumentos_extra(object):
    def setupUi(self, ventana_argumentos_extra):
        ventana_argumentos_extra.setObjectName("ventana_argumentos_extra")
        ventana_argumentos_extra.setWindowModality(QtCore.Qt.ApplicationModal)
        ventana_argumentos_extra.resize(494, 664)
        ventana_argumentos_extra.setMinimumSize(QtCore.QSize(300, 0))
        ventana_argumentos_extra.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        ventana_argumentos_extra.setWindowTitle("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ventana_argumentos_extra)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(ventana_argumentos_extra)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.arbol = ArbolWgts(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(98)
        sizePolicy.setHeightForWidth(self.arbol.sizePolicy().hasHeightForWidth())
        self.arbol.setSizePolicy(sizePolicy)
        self.arbol.setAutoScroll(False)
        self.arbol.setAlternatingRowColors(True)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.arbol.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.arbol.setHeaderHidden(True)
        self.arbol.setObjectName("arbol")
        self.arbol.headerItem().setText(0, "1")
        self.arbol.header().setVisible(False)
        self.arbol.header().setDefaultSectionSize(100)
        self.arbol.header().setMinimumSectionSize(50)
        self.arbol.header().setStretchLastSection(False)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_args = QtWidgets.QLabel(self.groupBox)
        self.lbl_args.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_args.setObjectName("lbl_args")
        self.verticalLayout.addWidget(self.lbl_args)
        self.campo_args = QtWidgets.QPlainTextEdit(self.groupBox)
        self.campo_args.setObjectName("campo_args")
        self.verticalLayout.addWidget(self.campo_args)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.btn_guardar_preset = QtWidgets.QPushButton(self.groupBox)
        self.btn_guardar_preset.setObjectName("btn_guardar_preset")
        self.horizontalLayout_9.addWidget(self.btn_guardar_preset)
        self.btn_limpiar = QtWidgets.QPushButton(self.groupBox)
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.horizontalLayout_9.addWidget(self.btn_limpiar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addWidget(self.splitter)
        self.botones_generales = QtWidgets.QDialogButtonBox(ventana_argumentos_extra)
        self.botones_generales.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.botones_generales.setObjectName("botones_generales")
        self.verticalLayout_2.addWidget(self.botones_generales)

        self.retranslateUi(ventana_argumentos_extra)
        QtCore.QMetaObject.connectSlotsByName(ventana_argumentos_extra)

    def retranslateUi(self, ventana_argumentos_extra):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_args.setText(_translate("ventana_argumentos_extra", "Argumentos:"))
        self.btn_guardar_preset.setText(_translate("ventana_argumentos_extra", "Guardar como preset"))
        self.btn_limpiar.setText(_translate("ventana_argumentos_extra", "Limpiar"))
from ui.arbol_wgts import ArbolWgts
