# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blend_no_encontrado.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_item_no_encontrado(object):
    def setupUi(self, item_no_encontrado):
        item_no_encontrado.setObjectName("item_no_encontrado")
        item_no_encontrado.setWindowModality(QtCore.Qt.ApplicationModal)
        item_no_encontrado.resize(353, 126)
        item_no_encontrado.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(item_no_encontrado)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.mensaje_blend_no_encontrado = QtWidgets.QLabel(item_no_encontrado)
        self.mensaje_blend_no_encontrado.setObjectName("mensaje_blend_no_encontrado")
        self.horizontalLayout_2.addWidget(self.mensaje_blend_no_encontrado)
        self.nombre_blend = QtWidgets.QLabel(item_no_encontrado)
        self.nombre_blend.setObjectName("nombre_blend")
        self.horizontalLayout_2.addWidget(self.nombre_blend)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.boton_reubicar = QtWidgets.QPushButton(item_no_encontrado)
        self.boton_reubicar.setObjectName("boton_reubicar")
        self.gridLayout.addWidget(self.boton_reubicar, 0, 1, 1, 1)
        self.ruta_blend = QtWidgets.QLineEdit(item_no_encontrado)
        self.ruta_blend.setMinimumSize(QtCore.QSize(0, 0))
        self.ruta_blend.setObjectName("ruta_blend")
        self.gridLayout.addWidget(self.ruta_blend, 0, 0, 1, 1)
        self.chk_adivinar = QtWidgets.QCheckBox(item_no_encontrado)
        self.chk_adivinar.setObjectName("chk_adivinar")
        self.gridLayout.addWidget(self.chk_adivinar, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_offline = QtWidgets.QPushButton(item_no_encontrado)
        self.btn_offline.setObjectName("btn_offline")
        self.horizontalLayout_3.addWidget(self.btn_offline)
        self.boton_omitir = QtWidgets.QPushButton(item_no_encontrado)
        self.boton_omitir.setObjectName("boton_omitir")
        self.horizontalLayout_3.addWidget(self.boton_omitir)
        self.boton_cancelar = QtWidgets.QPushButton(item_no_encontrado)
        self.boton_cancelar.setObjectName("boton_cancelar")
        self.horizontalLayout_3.addWidget(self.boton_cancelar)
        self.boton_aceptar = QtWidgets.QPushButton(item_no_encontrado)
        self.boton_aceptar.setObjectName("boton_aceptar")
        self.horizontalLayout_3.addWidget(self.boton_aceptar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(item_no_encontrado)
        QtCore.QMetaObject.connectSlotsByName(item_no_encontrado)

    def retranslateUi(self, item_no_encontrado):
        _translate = QtCore.QCoreApplication.translate
        item_no_encontrado.setWindowTitle(_translate("item_no_encontrado", "Blend not found!"))
        self.mensaje_blend_no_encontrado.setText(_translate("item_no_encontrado", "Blend not found:"))
        self.nombre_blend.setText(_translate("item_no_encontrado", "Blend Name"))
        self.boton_reubicar.setText(_translate("item_no_encontrado", "Relocate"))
        self.chk_adivinar.setText(_translate("item_no_encontrado", "Try to guess the path for other missing blends"))
        self.btn_offline.setText(_translate("item_no_encontrado", "Offline"))
        self.boton_omitir.setText(_translate("item_no_encontrado", "Skip"))
        self.boton_cancelar.setText(_translate("item_no_encontrado", "Cancel"))
        self.boton_aceptar.setText(_translate("item_no_encontrado", "Accept"))
