# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiar_blender.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_cambiar_blender(object):
    def setupUi(self, ventana_cambiar_blender):
        ventana_cambiar_blender.setObjectName("ventana_cambiar_blender")
        ventana_cambiar_blender.setWindowModality(QtCore.Qt.ApplicationModal)
        ventana_cambiar_blender.resize(379, 139)
        ventana_cambiar_blender.setWindowTitle("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ventana_cambiar_blender)
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(ventana_cambiar_blender)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selector_tag_blender = QtWidgets.QComboBox(self.groupBox)
        self.selector_tag_blender.setMinimumSize(QtCore.QSize(150, 0))
        self.selector_tag_blender.setEditable(True)
        self.selector_tag_blender.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.selector_tag_blender.setObjectName("selector_tag_blender")
        self.horizontalLayout.addWidget(self.selector_tag_blender)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_agregar_blender = QtWidgets.QToolButton(self.groupBox)
        self.btn_agregar_blender.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_agregar_blender.setText("")
        self.btn_agregar_blender.setObjectName("btn_agregar_blender")
        self.horizontalLayout_3.addWidget(self.btn_agregar_blender)
        self.btn_quitar_blender = QtWidgets.QToolButton(self.groupBox)
        self.btn_quitar_blender.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_quitar_blender.setText("")
        self.btn_quitar_blender.setObjectName("btn_quitar_blender")
        self.horizontalLayout_3.addWidget(self.btn_quitar_blender)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.lbl_ruta_blender_alt = QtWidgets.QLabel(self.groupBox)
        self.lbl_ruta_blender_alt.setObjectName("lbl_ruta_blender_alt")
        self.gridLayout.addWidget(self.lbl_ruta_blender_alt, 1, 0, 1, 1)
        self.ruta_blender_alt = QtWidgets.QLineEdit(self.groupBox)
        self.ruta_blender_alt.setMinimumSize(QtCore.QSize(250, 0))
        self.ruta_blender_alt.setObjectName("ruta_blender_alt")
        self.gridLayout.addWidget(self.ruta_blender_alt, 1, 1, 1, 1)
        self.lbl_identificador_blender_alt = QtWidgets.QLabel(self.groupBox)
        self.lbl_identificador_blender_alt.setObjectName("lbl_identificador_blender_alt")
        self.gridLayout.addWidget(self.lbl_identificador_blender_alt, 0, 0, 1, 1)
        self.btn_explorar = QtWidgets.QPushButton(self.groupBox)
        self.btn_explorar.setText("")
        self.btn_explorar.setObjectName("btn_explorar")
        self.gridLayout.addWidget(self.btn_explorar, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_distribuir = QtWidgets.QPushButton(ventana_cambiar_blender)
        self.btn_distribuir.setObjectName("btn_distribuir")
        self.horizontalLayout_2.addWidget(self.btn_distribuir)
        self.botones_generales = QtWidgets.QDialogButtonBox(ventana_cambiar_blender)
        self.botones_generales.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.botones_generales.setObjectName("botones_generales")
        self.horizontalLayout_2.addWidget(self.botones_generales)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ventana_cambiar_blender)
        QtCore.QMetaObject.connectSlotsByName(ventana_cambiar_blender)

    def retranslateUi(self, ventana_cambiar_blender):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_ruta_blender_alt.setText(_translate("ventana_cambiar_blender", "Ruta:"))
        self.lbl_identificador_blender_alt.setText(_translate("ventana_cambiar_blender", "Nombre:"))
        self.btn_distribuir.setText(_translate("ventana_cambiar_blender", "Distribuir"))
