# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_watchfolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config_watchfolder(object):
    def setupUi(self, config_watchfolder):
        config_watchfolder.setObjectName("config_watchfolder")
        config_watchfolder.resize(382, 322)
        self.verticalLayout = QtWidgets.QVBoxLayout(config_watchfolder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_carpeta = QtWidgets.QLabel(config_watchfolder)
        self.lbl_carpeta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_carpeta.setObjectName("lbl_carpeta")
        self.verticalLayout.addWidget(self.lbl_carpeta)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_carpetas = QtWidgets.QVBoxLayout()
        self.layout_carpetas.setContentsMargins(-1, -1, -1, 5)
        self.layout_carpetas.setObjectName("layout_carpetas")
        self.verticalLayout_4.addLayout(self.layout_carpetas)
        self.hl_boton_agregar = QtWidgets.QHBoxLayout()
        self.hl_boton_agregar.setObjectName("hl_boton_agregar")
        self.btn_agregar = QtWidgets.QPushButton(config_watchfolder)
        self.btn_agregar.setObjectName("btn_agregar")
        self.hl_boton_agregar.addWidget(self.btn_agregar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_boton_agregar.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.hl_boton_agregar)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.grupo_args_extra = QtWidgets.QGroupBox(config_watchfolder)
        self.grupo_args_extra.setBaseSize(QtCore.QSize(0, 10))
        self.grupo_args_extra.setObjectName("grupo_args_extra")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grupo_args_extra)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ventana_argsExtra = QtWidgets.QPushButton(self.grupo_args_extra)
        self.btn_ventana_argsExtra.setObjectName("btn_ventana_argsExtra")
        self.horizontalLayout.addWidget(self.btn_ventana_argsExtra)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.campo_argsExtra = QtWidgets.QPlainTextEdit(self.grupo_args_extra)
        self.campo_argsExtra.setObjectName("campo_argsExtra")
        self.verticalLayout_5.addWidget(self.campo_argsExtra)
        self.verticalLayout.addWidget(self.grupo_args_extra)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_setear = QtWidgets.QPushButton(config_watchfolder)
        self.btn_setear.setObjectName("btn_setear")
        self.horizontalLayout_2.addWidget(self.btn_setear)
        self.btn_cancelar = QtWidgets.QPushButton(config_watchfolder)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout_2.addWidget(self.btn_cancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(config_watchfolder)
        QtCore.QMetaObject.connectSlotsByName(config_watchfolder)

    def retranslateUi(self, config_watchfolder):
        _translate = QtCore.QCoreApplication.translate
        config_watchfolder.setWindowTitle(_translate("config_watchfolder", "Watchfolder"))
        self.lbl_carpeta.setText(_translate("config_watchfolder", "Watchfolders:"))
        self.btn_agregar.setText(_translate("config_watchfolder", "Agregar"))
        self.grupo_args_extra.setTitle(_translate("config_watchfolder", "Argumentos Extra"))
        self.btn_ventana_argsExtra.setText(_translate("config_watchfolder", "Ventana Argumentos Extra"))
        self.btn_setear.setText(_translate("config_watchfolder", "Aceptar"))
        self.btn_cancelar.setText(_translate("config_watchfolder", "Cancelar"))
