# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_modo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_modo_custom(object):
    def setupUi(self, ventana_modo_custom):
        ventana_modo_custom.setObjectName("ventana_modo_custom")
        ventana_modo_custom.resize(518, 516)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_modo_custom)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(ventana_modo_custom)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_modo_custom)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.aceptar_cancelar.setCenterButtons(False)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(ventana_modo_custom)
        self.aceptar_cancelar.accepted.connect(ventana_modo_custom.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(ventana_modo_custom.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ventana_modo_custom)

    def retranslateUi(self, ventana_modo_custom):
        _translate = QtCore.QCoreApplication.translate
        ventana_modo_custom.setWindowTitle(_translate("ventana_modo_custom", "Dialog"))
