# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogo_reubicar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_reubicar(object):
    def setupUi(self, ventana_reubicar):
        ventana_reubicar.setObjectName("ventana_reubicar")
        ventana_reubicar.resize(476, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_reubicar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_anterior = QtWidgets.QLabel(ventana_reubicar)
        self.lbl_anterior.setObjectName("lbl_anterior")
        self.horizontalLayout.addWidget(self.lbl_anterior)
        self.path_viejo = QtWidgets.QLabel(ventana_reubicar)
        self.path_viejo.setObjectName("path_viejo")
        self.horizontalLayout.addWidget(self.path_viejo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_nuevo = QtWidgets.QLabel(ventana_reubicar)
        self.lbl_nuevo.setObjectName("lbl_nuevo")
        self.horizontalLayout_3.addWidget(self.lbl_nuevo)
        self.path_nuevo = QtWidgets.QLineEdit(ventana_reubicar)
        self.path_nuevo.setObjectName("path_nuevo")
        self.horizontalLayout_3.addWidget(self.path_nuevo)
        self.btn_explorar = QtWidgets.QPushButton(ventana_reubicar)
        self.btn_explorar.setObjectName("btn_explorar")
        self.horizontalLayout_3.addWidget(self.btn_explorar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_reubicar)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(ventana_reubicar)
        self.aceptar_cancelar.accepted.connect(ventana_reubicar.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(ventana_reubicar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ventana_reubicar)

    def retranslateUi(self, ventana_reubicar):
        _translate = QtCore.QCoreApplication.translate
        ventana_reubicar.setWindowTitle(_translate("ventana_reubicar", "Dialog"))
        self.lbl_anterior.setText(_translate("ventana_reubicar", "Anterior:"))
        self.path_viejo.setText(_translate("ventana_reubicar", "path_anterior"))
        self.lbl_nuevo.setText(_translate("ventana_reubicar", "Nuevo:"))
        self.btn_explorar.setText(_translate("ventana_reubicar", "Explorar"))
