# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_skin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editor_skin(object):
    def setupUi(self, editor_skin):
        editor_skin.setObjectName("editor_skin")
        editor_skin.resize(327, 388)
        self.verticalLayout = QtWidgets.QVBoxLayout(editor_skin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_selector_skin = QtWidgets.QLabel(editor_skin)
        self.lbl_selector_skin.setObjectName("lbl_selector_skin")
        self.horizontalLayout.addWidget(self.lbl_selector_skin)
        self.selector_skin = QtWidgets.QComboBox(editor_skin)
        self.selector_skin.setEditable(False)
        self.selector_skin.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.selector_skin.setObjectName("selector_skin")
        self.horizontalLayout.addWidget(self.selector_skin)
        self.test1 = QtWidgets.QToolButton(editor_skin)
        self.test1.setObjectName("test1")
        self.horizontalLayout.addWidget(self.test1)
        self.test2 = QtWidgets.QToolButton(editor_skin)
        self.test2.setEnabled(False)
        self.test2.setObjectName("test2")
        self.horizontalLayout.addWidget(self.test2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.arbol = ArbolWgts(editor_skin)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.arbol.setIndentation(20)
        self.arbol.setRootIsDecorated(True)
        self.arbol.setHeaderHidden(True)
        self.arbol.setColumnCount(2)
        self.arbol.setObjectName("arbol")
        self.arbol.header().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.arbol)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(editor_skin)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(editor_skin)
        self.aceptar_cancelar.accepted.connect(editor_skin.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(editor_skin.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(editor_skin)

    def retranslateUi(self, editor_skin):
        _translate = QtCore.QCoreApplication.translate
        editor_skin.setWindowTitle(_translate("editor_skin", "Dialog"))
        self.lbl_selector_skin.setText(_translate("editor_skin", "Custom skin"))
        self.test1.setText(_translate("editor_skin", "..."))
        self.test2.setText(_translate("editor_skin", "..."))
        self.arbol.setSortingEnabled(False)
        self.arbol.headerItem().setText(1, _translate("editor_skin", "New Column"))
from ui.arbol_wgts import ArbolWgts
