# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_modo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditorModos(object):
    def setupUi(self, EditorModos):
        EditorModos.setObjectName("EditorModos")
        EditorModos.resize(518, 516)
        EditorModos.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorModos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.arbol = ArbolWgts(EditorModos)
        self.arbol.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arbol.setFrameShadow(QtWidgets.QFrame.Plain)
        self.arbol.setAlternatingRowColors(False)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.arbol.setIndentation(15)
        self.arbol.setUniformRowHeights(False)
        self.arbol.setHeaderHidden(True)
        self.arbol.setObjectName("arbol")
        self.arbol.headerItem().setText(0, "1")
        self.arbol.header().setVisible(False)
        self.arbol.header().setCascadingSectionResizes(True)
        self.arbol.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.arbol)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(EditorModos)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setCenterButtons(False)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(EditorModos)
        self.aceptar_cancelar.accepted.connect(EditorModos.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(EditorModos.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditorModos)

    def retranslateUi(self, EditorModos):
        _translate = QtCore.QCoreApplication.translate
        EditorModos.setWindowTitle(_translate("EditorModos", "Custom Modes"))
from ui.arbol_wgts import ArbolWgts
