# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup(object):
    def setupUi(self, popup):
        popup.setObjectName("popup")
        popup.resize(342, 279)
        self.verticalLayout = QtWidgets.QVBoxLayout(popup)
        self.verticalLayout.setContentsMargins(20, 10, 20, 6)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ico_info = QtWidgets.QLabel(popup)
        self.ico_info.setText("")
        self.ico_info.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_info.setObjectName("ico_info")
        self.verticalLayout.addWidget(self.ico_info)
        self.contenedor_texto = QtWidgets.QTextBrowser(popup)
        self.contenedor_texto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contenedor_texto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.contenedor_texto.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.contenedor_texto.setObjectName("contenedor_texto")
        self.verticalLayout.addWidget(self.contenedor_texto)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(popup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(popup)
        self.buttonBox.clicked['QAbstractButton*'].connect(popup.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(popup)

    def retranslateUi(self, popup):
        _translate = QtCore.QCoreApplication.translate
        popup.setWindowTitle(_translate("popup", "Dialog"))
