# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numero_splits.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo_numero_items(object):
    def setupUi(self, dialogo_numero_items):
        dialogo_numero_items.setObjectName("dialogo_numero_items")
        dialogo_numero_items.resize(273, 68)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogo_numero_items)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_numero_items = QtWidgets.QLabel(dialogo_numero_items)
        self.lbl_numero_items.setObjectName("lbl_numero_items")
        self.horizontalLayout.addWidget(self.lbl_numero_items)
        self.numero_items = QtWidgets.QSpinBox(dialogo_numero_items)
        self.numero_items.setMinimum(2)
        self.numero_items.setMaximum(1000)
        self.numero_items.setProperty("value", 2)
        self.numero_items.setObjectName("numero_items")
        self.horizontalLayout.addWidget(self.numero_items)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(dialogo_numero_items)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(dialogo_numero_items)
        self.aceptar_cancelar.accepted.connect(dialogo_numero_items.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(dialogo_numero_items.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogo_numero_items)

    def retranslateUi(self, dialogo_numero_items):
        _translate = QtCore.QCoreApplication.translate
        dialogo_numero_items.setWindowTitle(_translate("dialogo_numero_items", "Dialog"))
        self.lbl_numero_items.setText(_translate("dialogo_numero_items", "Numero de items en los que partir el rango:"))
