# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_wgt_nombrado.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nombrado_salida(object):
    def setupUi(self, nombrado_salida):
        nombrado_salida.setObjectName("nombrado_salida")
        nombrado_salida.resize(396, 114)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(nombrado_salida)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grupo_nombrado = QtWidgets.QGroupBox(nombrado_salida)
        self.grupo_nombrado.setMinimumSize(QtCore.QSize(0, 0))
        self.grupo_nombrado.setObjectName("grupo_nombrado")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grupo_nombrado)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chk_nombrado = QtWidgets.QCheckBox(self.grupo_nombrado)
        self.chk_nombrado.setObjectName("chk_nombrado")
        self.horizontalLayout_3.addWidget(self.chk_nombrado)
        self.selector_preset = QtWidgets.QComboBox(self.grupo_nombrado)
        self.selector_preset.setMinimumSize(QtCore.QSize(180, 0))
        self.selector_preset.setBaseSize(QtCore.QSize(0, 0))
        self.selector_preset.setObjectName("selector_preset")
        self.horizontalLayout_3.addWidget(self.selector_preset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_opciones_nombrado = QtWidgets.QPushButton(self.grupo_nombrado)
        self.btn_opciones_nombrado.setObjectName("btn_opciones_nombrado")
        self.horizontalLayout_4.addWidget(self.btn_opciones_nombrado)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.grupo_nombrado)

        self.retranslateUi(nombrado_salida)
        QtCore.QMetaObject.connectSlotsByName(nombrado_salida)

    def retranslateUi(self, nombrado_salida):
        _translate = QtCore.QCoreApplication.translate
        nombrado_salida.setWindowTitle(_translate("nombrado_salida", "Form"))
        self.grupo_nombrado.setTitle(_translate("nombrado_salida", "Nombrado de salida"))
        self.chk_nombrado.setText(_translate("nombrado_salida", "Usar preset:"))
        self.btn_opciones_nombrado.setText(_translate("nombrado_salida", "Opciones de nombrado"))
