# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ventana_blenders.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_blenders(object):
    def setupUi(self, ventana_blenders):
        ventana_blenders.setObjectName("ventana_blenders")
        ventana_blenders.resize(825, 305)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventana_blenders.sizePolicy().hasHeightForWidth())
        ventana_blenders.setSizePolicy(sizePolicy)
        ventana_blenders.setMinimumSize(QtCore.QSize(800, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_blenders)
        self.verticalLayout.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_agregar = QtWidgets.QToolButton(ventana_blenders)
        self.btn_agregar.setObjectName("btn_agregar")
        self.horizontalLayout.addWidget(self.btn_agregar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.arbol = ArbolWgts(ventana_blenders)
        self.arbol.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arbol.setFrameShadow(QtWidgets.QFrame.Plain)
        self.arbol.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.arbol.setAlternatingRowColors(False)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.arbol.setIndentation(20)
        self.arbol.setRootIsDecorated(False)
        self.arbol.setUniformRowHeights(False)
        self.arbol.setHeaderHidden(False)
        self.arbol.setObjectName("arbol")
        self.arbol.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.arbol.headerItem().setBackground(0, QtGui.QColor(0, 0, 0, 0))
        self.arbol.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.arbol.headerItem().setBackground(1, QtGui.QColor(0, 0, 0, 0))
        self.arbol.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.arbol.headerItem().setBackground(2, QtGui.QColor(0, 0, 0, 0))
        self.arbol.header().setVisible(True)
        self.verticalLayout.addWidget(self.arbol)
        self.btn_aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_blenders)
        self.btn_aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_aceptar_cancelar.setObjectName("btn_aceptar_cancelar")
        self.verticalLayout.addWidget(self.btn_aceptar_cancelar)

        self.retranslateUi(ventana_blenders)
        QtCore.QMetaObject.connectSlotsByName(ventana_blenders)

    def retranslateUi(self, ventana_blenders):
        _translate = QtCore.QCoreApplication.translate
        ventana_blenders.setWindowTitle(_translate("ventana_blenders", "Form"))
        self.btn_agregar.setText(_translate("ventana_blenders", "..."))
        self.arbol.headerItem().setText(0, _translate("ventana_blenders", "Tag"))
        self.arbol.headerItem().setText(1, _translate("ventana_blenders", "Version"))
        self.arbol.headerItem().setText(2, _translate("ventana_blenders", "Path"))
from ui.arbol_wgts import ArbolWgts
