# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_estimar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_estimar_tiempo(object):
    def setupUi(self, ventana_estimar_tiempo):
        ventana_estimar_tiempo.setObjectName("ventana_estimar_tiempo")
        ventana_estimar_tiempo.setWindowModality(QtCore.Qt.ApplicationModal)
        ventana_estimar_tiempo.resize(304, 162)
        ventana_estimar_tiempo.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_estimar_tiempo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.explicacion_base = QtWidgets.QPlainTextEdit(ventana_estimar_tiempo)
        self.explicacion_base.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.explicacion_base.setFrameShadow(QtWidgets.QFrame.Plain)
        self.explicacion_base.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.explicacion_base.setBackgroundVisible(True)
        self.explicacion_base.setObjectName("explicacion_base")
        self.verticalLayout.addWidget(self.explicacion_base)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_frames = QtWidgets.QLabel(ventana_estimar_tiempo)
        self.lbl_frames.setObjectName("lbl_frames")
        self.horizontalLayout.addWidget(self.lbl_frames)
        self.selector_frames = QtWidgets.QSpinBox(ventana_estimar_tiempo)
        self.selector_frames.setMinimum(1)
        self.selector_frames.setObjectName("selector_frames")
        self.horizontalLayout.addWidget(self.selector_frames)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lbl_estimado = QtWidgets.QLabel(ventana_estimar_tiempo)
        self.lbl_estimado.setObjectName("lbl_estimado")
        self.horizontalLayout_2.addWidget(self.lbl_estimado)
        self.estimado = QtWidgets.QLabel(ventana_estimar_tiempo)
        self.estimado.setObjectName("estimado")
        self.horizontalLayout_2.addWidget(self.estimado)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_calcular = QtWidgets.QPushButton(ventana_estimar_tiempo)
        self.btn_calcular.setObjectName("btn_calcular")
        self.horizontalLayout_3.addWidget(self.btn_calcular)
        self.btn_cancelar = QtWidgets.QPushButton(ventana_estimar_tiempo)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout_3.addWidget(self.btn_cancelar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_close = QtWidgets.QDialogButtonBox(ventana_estimar_tiempo)
        self.btn_close.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(ventana_estimar_tiempo)
        QtCore.QMetaObject.connectSlotsByName(ventana_estimar_tiempo)

    def retranslateUi(self, ventana_estimar_tiempo):
        _translate = QtCore.QCoreApplication.translate
        ventana_estimar_tiempo.setWindowTitle(_translate("ventana_estimar_tiempo", "Dialog"))
        self.explicacion_base.setPlainText(_translate("ventana_estimar_tiempo", "Estimate the total rendering time for the queue\n"
"by rendering one or more frames. The more frames used, the slower but more precise the estimation."))
        self.lbl_frames.setText(_translate("ventana_estimar_tiempo", "Frames"))
        self.lbl_estimado.setText(_translate("ventana_estimar_tiempo", "Total estimado:"))
        self.estimado.setText(_translate("ventana_estimar_tiempo", "No calculado"))
        self.btn_calcular.setText(_translate("ventana_estimar_tiempo", "Calcular"))
        self.btn_cancelar.setText(_translate("ventana_estimar_tiempo", "Cancelar"))
