# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_tareas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_tareas(object):
    def setupUi(self, ventana_tareas):
        ventana_tareas.setObjectName("ventana_tareas")
        ventana_tareas.resize(456, 314)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_tareas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_explicacion = QtWidgets.QLabel(ventana_tareas)
        self.lbl_explicacion.setObjectName("lbl_explicacion")
        self.verticalLayout.addWidget(self.lbl_explicacion)
        self.arbol = ArbolWgts(ventana_tareas)
        self.arbol.setObjectName("arbol")
        self.verticalLayout.addWidget(self.arbol)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_tareas)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(ventana_tareas)
        self.aceptar_cancelar.accepted.connect(ventana_tareas.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(ventana_tareas.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ventana_tareas)

    def retranslateUi(self, ventana_tareas):
        _translate = QtCore.QCoreApplication.translate
        ventana_tareas.setWindowTitle(_translate("ventana_tareas", "Dialog"))
        self.lbl_explicacion.setText(_translate("ventana_tareas", "Correr archivo post-render"))
        self.arbol.headerItem().setText(0, _translate("ventana_tareas", "1"))
from ui.arbol_wgts import ArbolWgts
