# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_ventana_principal(object):
    def setupUi(self, ui_ventana_principal):
        ui_ventana_principal.setObjectName("ui_ventana_principal")
        ui_ventana_principal.resize(1078, 484)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ui_ventana_principal.sizePolicy().hasHeightForWidth())
        ui_ventana_principal.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/test_icono_chuchu2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ui_ventana_principal.setWindowIcon(icon)
        self.organizador_central = QtWidgets.QWidget(ui_ventana_principal)
        self.organizador_central.setObjectName("organizador_central")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.organizador_central)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.botonCF = QtWidgets.QPushButton(self.organizador_central)
        self.botonCF.setObjectName("botonCF")
        self.horizontalLayout_2.addWidget(self.botonCF)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line_4 = QtWidgets.QFrame(self.organizador_central)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.labelLoQue = QtWidgets.QLabel(self.organizador_central)
        self.labelLoQue.setObjectName("labelLoQue")
        self.horizontalLayout_2.addWidget(self.labelLoQue)
        self.selectorLoQue = QtWidgets.QComboBox(self.organizador_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectorLoQue.sizePolicy().hasHeightForWidth())
        self.selectorLoQue.setSizePolicy(sizePolicy)
        self.selectorLoQue.setMinimumSize(QtCore.QSize(0, 0))
        self.selectorLoQue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectorLoQue.setObjectName("selectorLoQue")
        self.selectorLoQue.addItem("")
        self.selectorLoQue.addItem("")
        self.horizontalLayout_2.addWidget(self.selectorLoQue)
        spacerItem3 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.botonAgregar = QtWidgets.QPushButton(self.organizador_central)
        self.botonAgregar.setObjectName("botonAgregar")
        self.horizontalLayout_2.addWidget(self.botonAgregar)
        self.botonQT = QtWidgets.QPushButton(self.organizador_central)
        self.botonQT.setObjectName("botonQT")
        self.horizontalLayout_2.addWidget(self.botonQT)
        self.botonQS = QtWidgets.QPushButton(self.organizador_central)
        self.botonQS.setObjectName("botonQS")
        self.horizontalLayout_2.addWidget(self.botonQS)
        self.botonDS = QtWidgets.QPushButton(self.organizador_central)
        self.botonDS.setObjectName("botonDS")
        self.horizontalLayout_2.addWidget(self.botonDS)
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.botonRS = QtWidgets.QPushButton(self.organizador_central)
        self.botonRS.setObjectName("botonRS")
        self.horizontalLayout_2.addWidget(self.botonRS)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.line_3 = QtWidgets.QFrame(self.organizador_central)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.boton_info = QtWidgets.QPushButton(self.organizador_central)
        self.boton_info.setMinimumSize(QtCore.QSize(100, 0))
        self.boton_info.setMaximumSize(QtCore.QSize(50, 16777215))
        self.boton_info.setObjectName("boton_info")
        self.horizontalLayout_2.addWidget(self.boton_info)
        spacerItem7 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tablaPrincipal = QtWidgets.QTreeWidget(self.organizador_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaPrincipal.sizePolicy().hasHeightForWidth())
        self.tablaPrincipal.setSizePolicy(sizePolicy)
        self.tablaPrincipal.setMinimumSize(QtCore.QSize(750, 350))
        self.tablaPrincipal.setSizeIncrement(QtCore.QSize(0, 0))
        self.tablaPrincipal.setAcceptDrops(True)
        self.tablaPrincipal.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablaPrincipal.setProperty("showDropIndicator", True)
        self.tablaPrincipal.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tablaPrincipal.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tablaPrincipal.setRootIsDecorated(False)
        self.tablaPrincipal.setItemsExpandable(False)
        self.tablaPrincipal.setExpandsOnDoubleClick(False)
        self.tablaPrincipal.setObjectName("tablaPrincipal")
        self.horizontalLayout_3.addWidget(self.tablaPrincipal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.boton_reajustar_modo = QtWidgets.QPushButton(self.organizador_central)
        self.boton_reajustar_modo.setObjectName("boton_reajustar_modo")
        self.horizontalLayout.addWidget(self.boton_reajustar_modo)
        self.boton_cambiar_escena = QtWidgets.QPushButton(self.organizador_central)
        self.boton_cambiar_escena.setObjectName("boton_cambiar_escena")
        self.horizontalLayout.addWidget(self.boton_cambiar_escena)
        self.boton_cambiar_rango = QtWidgets.QPushButton(self.organizador_central)
        self.boton_cambiar_rango.setObjectName("boton_cambiar_rango")
        self.horizontalLayout.addWidget(self.boton_cambiar_rango)
        self.boton_cambiar_version = QtWidgets.QPushButton(self.organizador_central)
        self.boton_cambiar_version.setObjectName("boton_cambiar_version")
        self.horizontalLayout.addWidget(self.boton_cambiar_version)
        self.boton_argumentos_extra = QtWidgets.QPushButton(self.organizador_central)
        self.boton_argumentos_extra.setObjectName("boton_argumentos_extra")
        self.horizontalLayout.addWidget(self.boton_argumentos_extra)
        self.boton_dispositivos = QtWidgets.QPushButton(self.organizador_central)
        self.boton_dispositivos.setObjectName("boton_dispositivos")
        self.horizontalLayout.addWidget(self.boton_dispositivos)
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.line_2 = QtWidgets.QFrame(self.organizador_central)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem10 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.boton_explorar_blend = QtWidgets.QPushButton(self.organizador_central)
        self.boton_explorar_blend.setObjectName("boton_explorar_blend")
        self.horizontalLayout.addWidget(self.boton_explorar_blend)
        self.boton_explorar_output = QtWidgets.QPushButton(self.organizador_central)
        self.boton_explorar_output.setObjectName("boton_explorar_output")
        self.horizontalLayout.addWidget(self.boton_explorar_output)
        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.line = QtWidgets.QFrame(self.organizador_central)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem12 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.botonRender = QtWidgets.QPushButton(self.organizador_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRender.sizePolicy().hasHeightForWidth())
        self.botonRender.setSizePolicy(sizePolicy)
        self.botonRender.setMinimumSize(QtCore.QSize(0, 50))
        self.botonRender.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.botonRender.setFont(font)
        self.botonRender.setObjectName("botonRender")
        self.horizontalLayout.addWidget(self.botonRender)
        spacerItem13 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        ui_ventana_principal.setCentralWidget(self.organizador_central)
        self.statusBar = QtWidgets.QStatusBar(ui_ventana_principal)
        self.statusBar.setObjectName("statusBar")
        ui_ventana_principal.setStatusBar(self.statusBar)

        self.retranslateUi(ui_ventana_principal)
        QtCore.QMetaObject.connectSlotsByName(ui_ventana_principal)

    def retranslateUi(self, ui_ventana_principal):
        _translate = QtCore.QCoreApplication.translate
        ui_ventana_principal.setWindowTitle(_translate("ui_ventana_principal", "Chuchurenderon!"))
        self.botonCF.setText(_translate("ui_ventana_principal", "Configuración"))
        self.labelLoQue.setText(_translate("ui_ventana_principal", "Añadir cómo:"))
        self.selectorLoQue.setItemText(0, _translate("ui_ventana_principal", "Animación"))
        self.selectorLoQue.setItemText(1, _translate("ui_ventana_principal", "Frames"))
        self.botonAgregar.setText(_translate("ui_ventana_principal", "Añadir Archivos"))
        self.botonQT.setText(_translate("ui_ventana_principal", "Quitar Todos"))
        self.botonQS.setText(_translate("ui_ventana_principal", "Quitar Seleccionados"))
        self.botonDS.setText(_translate("ui_ventana_principal", "Duplicar seleccionados"))
        self.botonRS.setText(_translate("ui_ventana_principal", "Recuperar sesión anterior"))
        self.boton_info.setText(_translate("ui_ventana_principal", "Info"))
        self.tablaPrincipal.headerItem().setText(0, _translate("ui_ventana_principal", "Ruta"))
        self.tablaPrincipal.headerItem().setText(1, _translate("ui_ventana_principal", "Archivo"))
        self.tablaPrincipal.headerItem().setText(2, _translate("ui_ventana_principal", "Lo Qué"))
        self.tablaPrincipal.headerItem().setText(3, _translate("ui_ventana_principal", "Estado"))
        self.tablaPrincipal.headerItem().setText(4, _translate("ui_ventana_principal", "Blender"))
        self.tablaPrincipal.headerItem().setText(5, _translate("ui_ventana_principal", "Escena"))
        self.tablaPrincipal.headerItem().setText(6, _translate("ui_ventana_principal", "Inicio"))
        self.tablaPrincipal.headerItem().setText(7, _translate("ui_ventana_principal", "Fin"))
        self.boton_reajustar_modo.setText(_translate("ui_ventana_principal", "Reajustar\n"
" Modo"))
        self.boton_cambiar_escena.setText(_translate("ui_ventana_principal", "Cambiar \n"
"Escena"))
        self.boton_cambiar_rango.setText(_translate("ui_ventana_principal", "Cambiar Rango \n"
"de frames"))
        self.boton_cambiar_version.setText(_translate("ui_ventana_principal", "Cambiar versión \n"
" de Blender"))
        self.boton_argumentos_extra.setText(_translate("ui_ventana_principal", "Argumentos \n"
" Extra"))
        self.boton_dispositivos.setText(_translate("ui_ventana_principal", "Elegir\n"
" dispositivos (Cycles)"))
        self.boton_explorar_blend.setText(_translate("ui_ventana_principal", "Explorar ruta\n"
" Blend"))
        self.boton_explorar_output.setText(_translate("ui_ventana_principal", "Explorar ruta \n"
" Output"))
        self.botonRender.setText(_translate("ui_ventana_principal", "  TIRAR RENDERS!  "))

import recursos_chuchurenderon_rc
