# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_escenas_cambiar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_cambiar_escenas(object):
    def setupUi(self, ventana_cambiar_escenas):
        ventana_cambiar_escenas.setObjectName("ventana_cambiar_escenas")
        ventana_cambiar_escenas.setWindowModality(QtCore.Qt.ApplicationModal)
        ventana_cambiar_escenas.resize(262, 308)
        self.gridLayout_2 = QtWidgets.QGridLayout(ventana_cambiar_escenas)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_leer_escenas = QtWidgets.QPushButton(ventana_cambiar_escenas)
        self.btn_leer_escenas.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_leer_escenas.setObjectName("btn_leer_escenas")
        self.horizontalLayout_2.addWidget(self.btn_leer_escenas)
        self.btn_elegir_todas = QtWidgets.QPushButton(ventana_cambiar_escenas)
        self.btn_elegir_todas.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_elegir_todas.setObjectName("btn_elegir_todas")
        self.horizontalLayout_2.addWidget(self.btn_elegir_todas)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.opcion_escribir_escena = QtWidgets.QRadioButton(ventana_cambiar_escenas)
        self.opcion_escribir_escena.setObjectName("opcion_escribir_escena")
        self.horizontalLayout.addWidget(self.opcion_escribir_escena)
        self.nombre_escena = QtWidgets.QLineEdit(ventana_cambiar_escenas)
        self.nombre_escena.setMinimumSize(QtCore.QSize(120, 0))
        self.nombre_escena.setObjectName("nombre_escena")
        self.horizontalLayout.addWidget(self.nombre_escena)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.opcion_elegir_escenas = QtWidgets.QRadioButton(ventana_cambiar_escenas)
        self.opcion_elegir_escenas.setObjectName("opcion_elegir_escenas")
        self.gridLayout_2.addWidget(self.opcion_elegir_escenas, 3, 0, 1, 1)
        self.boton_aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_cambiar_escenas)
        self.boton_aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.boton_aceptar_cancelar.setObjectName("boton_aceptar_cancelar")
        self.gridLayout_2.addWidget(self.boton_aceptar_cancelar, 7, 0, 1, 1)
        self.lista_escenas = QtWidgets.QListWidget(ventana_cambiar_escenas)
        self.lista_escenas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.lista_escenas.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lista_escenas.setObjectName("lista_escenas")
        self.gridLayout_2.addWidget(self.lista_escenas, 4, 0, 1, 1)
        self.opcion_escena_activa = QtWidgets.QRadioButton(ventana_cambiar_escenas)
        self.opcion_escena_activa.setObjectName("opcion_escena_activa")
        self.gridLayout_2.addWidget(self.opcion_escena_activa, 0, 0, 1, 1)

        self.retranslateUi(ventana_cambiar_escenas)
        QtCore.QMetaObject.connectSlotsByName(ventana_cambiar_escenas)

    def retranslateUi(self, ventana_cambiar_escenas):
        _translate = QtCore.QCoreApplication.translate
        ventana_cambiar_escenas.setWindowTitle(_translate("ventana_cambiar_escenas", "Cambiar escena"))
        self.btn_leer_escenas.setText(_translate("ventana_cambiar_escenas", "Read blend\'s scenes"))
        self.btn_elegir_todas.setText(_translate("ventana_cambiar_escenas", "Choose all"))
        self.opcion_escribir_escena.setText(_translate("ventana_cambiar_escenas", "Enter scene\'s name"))
        self.opcion_elegir_escenas.setText(_translate("ventana_cambiar_escenas", "Select scene(s) to add to the queue:"))
        self.opcion_escena_activa.setText(_translate("ventana_cambiar_escenas", "Use blend\'s active scene"))
