# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_dispositivos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_dispositivos(object):
    def setupUi(self, ventana_dispositivos):
        ventana_dispositivos.setObjectName("ventana_dispositivos")
        ventana_dispositivos.setWindowModality(QtCore.Qt.WindowModal)
        ventana_dispositivos.resize(263, 435)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_dispositivos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_btn_encontrar = QtWidgets.QHBoxLayout()
        self.layout_btn_encontrar.setObjectName("layout_btn_encontrar")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_btn_encontrar.addItem(spacerItem)
        self.btn_encontrar = QtWidgets.QPushButton(ventana_dispositivos)
        self.btn_encontrar.setObjectName("btn_encontrar")
        self.layout_btn_encontrar.addWidget(self.btn_encontrar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_btn_encontrar.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_btn_encontrar)
        self.arbol = ArbolWgts(ventana_dispositivos)
        self.arbol.setAlternatingRowColors(True)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.arbol.setHeaderHidden(True)
        self.arbol.setObjectName("arbol")
        self.arbol.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.arbol)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chk_parallel = QtWidgets.QCheckBox(ventana_dispositivos)
        self.chk_parallel.setObjectName("chk_parallel")
        self.horizontalLayout.addWidget(self.chk_parallel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_distribuir = QtWidgets.QPushButton(ventana_dispositivos)
        self.btn_distribuir.setEnabled(False)
        self.btn_distribuir.setObjectName("btn_distribuir")
        self.horizontalLayout_3.addWidget(self.btn_distribuir)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(ventana_dispositivos)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.horizontalLayout_3.addWidget(self.aceptar_cancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ventana_dispositivos)
        QtCore.QMetaObject.connectSlotsByName(ventana_dispositivos)

    def retranslateUi(self, ventana_dispositivos):
        _translate = QtCore.QCoreApplication.translate
        ventana_dispositivos.setWindowTitle(_translate("ventana_dispositivos", "Form"))
        self.btn_encontrar.setText(_translate("ventana_dispositivos", "PushButton"))
        self.chk_parallel.setText(_translate("ventana_dispositivos", "Parallel"))
        self.btn_distribuir.setText(_translate("ventana_dispositivos", "Distribuir"))
from ui.arbol_wgts import ArbolWgts
