# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_acerca_de(object):
    def setupUi(self, ventana_acerca_de):
        ventana_acerca_de.setObjectName("ventana_acerca_de")
        ventana_acerca_de.setWindowModality(QtCore.Qt.ApplicationModal)
        ventana_acerca_de.resize(672, 506)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventana_acerca_de.sizePolicy().hasHeightForWidth())
        ventana_acerca_de.setSizePolicy(sizePolicy)
        ventana_acerca_de.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventana_acerca_de)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(ventana_acerca_de)
        self.tabs.setObjectName("tabs")
        self.atajos = QtWidgets.QWidget()
        self.atajos.setObjectName("atajos")
        self.gridLayout = QtWidgets.QGridLayout(self.atajos)
        self.gridLayout.setObjectName("gridLayout")
        self.tabla_atajos = QtWidgets.QTreeWidget(self.atajos)
        self.tabla_atajos.setObjectName("tabla_atajos")
        self.gridLayout.addWidget(self.tabla_atajos, 1, 0, 1, 1)
        self.tabs.addTab(self.atajos, "")
        self.acerca_de = QtWidgets.QWidget()
        self.acerca_de.setObjectName("acerca_de")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.acerca_de)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo_principal = QtWidgets.QPushButton(self.acerca_de)
        self.titulo_principal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_principal.sizePolicy().hasHeightForWidth())
        self.titulo_principal.setSizePolicy(sizePolicy)
        self.titulo_principal.setMinimumSize(QtCore.QSize(600, 125))
        self.titulo_principal.setMaximumSize(QtCore.QSize(800, 120))
        self.titulo_principal.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.titulo_principal.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icono/iconos/icoapp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/iconos/icoapp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.titulo_principal.setIcon(icon)
        self.titulo_principal.setIconSize(QtCore.QSize(100, 100))
        self.titulo_principal.setCheckable(False)
        self.titulo_principal.setChecked(False)
        self.titulo_principal.setFlat(True)
        self.titulo_principal.setObjectName("titulo_principal")
        self.verticalLayout_2.addWidget(self.titulo_principal)
        self.acerca_de_bajada = QtWidgets.QLabel(self.acerca_de)
        self.acerca_de_bajada.setObjectName("acerca_de_bajada")
        self.verticalLayout_2.addWidget(self.acerca_de_bajada, 0, QtCore.Qt.AlignHCenter)
        self.lbl_version = QtWidgets.QLabel(self.acerca_de)
        self.lbl_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_2.addWidget(self.lbl_version)
        self.acerca_de_desarrollador = QtWidgets.QLabel(self.acerca_de)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        self.acerca_de_desarrollador.setFont(font)
        self.acerca_de_desarrollador.setAlignment(QtCore.Qt.AlignCenter)
        self.acerca_de_desarrollador.setObjectName("acerca_de_desarrollador")
        self.verticalLayout_2.addWidget(self.acerca_de_desarrollador)
        self.acerca_de_email = QtWidgets.QLabel(self.acerca_de)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        self.acerca_de_email.setFont(font)
        self.acerca_de_email.setAlignment(QtCore.Qt.AlignCenter)
        self.acerca_de_email.setObjectName("acerca_de_email")
        self.verticalLayout_2.addWidget(self.acerca_de_email)
        self.acerca_de_agradecimiento1 = QtWidgets.QLabel(self.acerca_de)
        self.acerca_de_agradecimiento1.setAlignment(QtCore.Qt.AlignCenter)
        self.acerca_de_agradecimiento1.setObjectName("acerca_de_agradecimiento1")
        self.verticalLayout_2.addWidget(self.acerca_de_agradecimiento1)
        spacerItem = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.acerca_de_notice = QtWidgets.QTextBrowser(self.acerca_de)
        self.acerca_de_notice.setObjectName("acerca_de_notice")
        self.verticalLayout_2.addWidget(self.acerca_de_notice)
        self.tabs.addTab(self.acerca_de, "")
        self.verticalLayout.addWidget(self.tabs)

        self.retranslateUi(ventana_acerca_de)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ventana_acerca_de)

    def retranslateUi(self, ventana_acerca_de):
        _translate = QtCore.QCoreApplication.translate
        ventana_acerca_de.setWindowTitle(_translate("ventana_acerca_de", "B-Renderon Info"))
        self.tabla_atajos.headerItem().setText(0, _translate("ventana_acerca_de", "Command"))
        self.tabla_atajos.headerItem().setText(1, _translate("ventana_acerca_de", "Shortcut"))
        self.tabs.setTabText(self.tabs.indexOf(self.atajos), _translate("ventana_acerca_de", "Shortcuts"))
        self.titulo_principal.setText(_translate("ventana_acerca_de", " B-Renderon"))
        self.acerca_de_bajada.setText(_translate("ventana_acerca_de", "Render manager para blender"))
        self.lbl_version.setText(_translate("ventana_acerca_de", "Version"))
        self.acerca_de_desarrollador.setText(_translate("ventana_acerca_de", "Copyright (C) 2024 Tomas Fenoglio"))
        self.acerca_de_email.setText(_translate("ventana_acerca_de", "<html><head/><body><p>Email: <a href=\"mailto:b.renderon@gmail.com\"><span style=\" text-decoration: underline; color:#0000ff;\">b.renderon@gmail.com</span></a></p></body></html>"))
        self.acerca_de_agradecimiento1.setText(_translate("ventana_acerca_de", "Many thanks to 只剩一瓶辣椒酱 for his help with the chinese tranaslation\n"
"and to Jesus for providing buttons icons"))
        self.acerca_de_notice.setHtml(_translate("ventana_acerca_de", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    This program uses </span><a href=\"https://riverbankcomputing.com/software/pyqt/\"><span style=\" text-decoration: underline; color:#0000ff;\">PyQt5</span></a><span style=\" font-family:\'Courier New\';\">, and trough it, </span><a href=\"https://www.qt.io\"><span style=\" text-decoration: underline; color:#0000ff;\">Qt</span></a><span style=\" font-family:\'Courier New\';\"> 5, under the terms of     </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    GNU General Public License version 3.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    This program is free software: you can redistribute it and/or modify</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    it under the terms of the GNU General Public License as published by</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    the Free Software Foundation, either version 3 of the License, or</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    any later version.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    To recive a copy of the source code files, please write to </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    </span><a href=\"mailto:b.renderon@gmail.com\"><span style=\" font-size:7.8pt; text-decoration: underline; color:#0000ff;\">b.renderon@gmail.com</span></a></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    This program is distributed in the hope that it will be useful,</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    but WITHOUT ANY WARRANTY; without even the implied warranty of</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    GNU General Public License for more details.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    You should have received a copy of the GNU General Public License</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">    along with this program.  If not, see </span><a href=\"https://www.gnu.org/licenses/\"><span style=\" font-family:\'Courier New\'; text-decoration: underline; color:#0000ff;\">https://www.gnu.org/licenses/</span></a><span style=\" font-family:\'Courier New\';\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">        </span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.acerca_de), _translate("ventana_acerca_de", "About B-Renderon"))
import recursos_chuchurenderon_rc
