# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watchfolders_arbol.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Watchfolders(object):
    def setupUi(self, Watchfolders):
        Watchfolders.setObjectName("Watchfolders")
        Watchfolders.resize(396, 516)
        Watchfolders.setWindowTitle("")
        Watchfolders.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Watchfolders)
        self.verticalLayout.setObjectName("verticalLayout")
        self.arbol = ArbolWgts(Watchfolders)
        self.arbol.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arbol.setAlternatingRowColors(False)
        self.arbol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.arbol.setIndentation(15)
        self.arbol.setUniformRowHeights(False)
        self.arbol.setHeaderHidden(False)
        self.arbol.setObjectName("arbol")
        self.arbol.headerItem().setText(0, "1")
        self.arbol.header().setVisible(True)
        self.verticalLayout.addWidget(self.arbol)
        self.aceptar_cancelar = QtWidgets.QDialogButtonBox(Watchfolders)
        self.aceptar_cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.aceptar_cancelar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aceptar_cancelar.setCenterButtons(False)
        self.aceptar_cancelar.setObjectName("aceptar_cancelar")
        self.verticalLayout.addWidget(self.aceptar_cancelar)

        self.retranslateUi(Watchfolders)
        self.aceptar_cancelar.accepted.connect(Watchfolders.accept) # type: ignore
        self.aceptar_cancelar.rejected.connect(Watchfolders.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Watchfolders)

    def retranslateUi(self, Watchfolders):
        pass
from ui.arbol_wgts import ArbolWgts
