# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_consola.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_consola(object):
    def setupUi(self, widget_consola):
        widget_consola.setObjectName("widget_consola")
        widget_consola.resize(614, 353)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(widget_consola)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_consola = QtWidgets.QPlainTextEdit(widget_consola)
        self.info_consola.setObjectName("info_consola")
        self.horizontalLayout_2.addWidget(self.info_consola)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_scrollfijo = QtWidgets.QToolButton(widget_consola)
        self.btn_scrollfijo.setCheckable(True)
        self.btn_scrollfijo.setArrowType(QtCore.Qt.UpArrow)
        self.btn_scrollfijo.setObjectName("btn_scrollfijo")
        self.verticalLayout.addWidget(self.btn_scrollfijo)
        self.btn_inicio = QtWidgets.QToolButton(widget_consola)
        self.btn_inicio.setObjectName("btn_inicio")
        self.verticalLayout.addWidget(self.btn_inicio)
        self.btn_fin = QtWidgets.QToolButton(widget_consola)
        self.btn_fin.setObjectName("btn_fin")
        self.verticalLayout.addWidget(self.btn_fin)
        self.btn_jump_frame = QtWidgets.QToolButton(widget_consola)
        self.btn_jump_frame.setObjectName("btn_jump_frame")
        self.verticalLayout.addWidget(self.btn_jump_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(widget_consola)
        QtCore.QMetaObject.connectSlotsByName(widget_consola)

    def retranslateUi(self, widget_consola):
        _translate = QtCore.QCoreApplication.translate
        widget_consola.setWindowTitle(_translate("widget_consola", "Form"))
        self.btn_scrollfijo.setText(_translate("widget_consola", "..."))
        self.btn_inicio.setText(_translate("widget_consola", "..."))
        self.btn_fin.setText(_translate("widget_consola", "..."))
        self.btn_jump_frame.setText(_translate("widget_consola", "..."))
