skins_extra = {"B-renderon Gray":
                   {"Main": {"10": {"color": "#c5c5c5", "nombre": "Window"},
                             "0": {"color": "#191919", "nombre": "Window Text"},
                             "9": {"color": "#c0c0c0", "nombre": "Base"},
                             "16": {"color": "#cccccc", "nombre": "Alternate Base"},
                             "6": {"color": "#242424", "nombre": "Text"}, "1": {"color": "#a1a1a1", "nombre": "Button"},
                             "8": {"color": "#353535", "nombre": "Button Text"},
                             "12": {"color": "#a0abc0", "nombre": "Highlight"},
                             "13": {"color": "#000000", "nombre": "Highlighted Text"},
                             "998": {"color": "#e59006", "nombre": "Checked watchfolders background"},
                             "999": {"color": "#A9FFFF", "nombre": "Checked scheduler background"},
                             "1000": {"color": "#FF0000", "nombre": "Checked shutdown background"}},
                    "Disabled": {"2": {"color": "#000000", "nombre": "Disabled Light"},
                                 "6": {"color": "#A9A9A9", "nombre": "Disabled Text"},
                                 "8": {"color": "#A9A9A9", "nombre": "Disabled Button Text"},
                                 "0": {"color": "#A9A9A9", "nombre": "Disabled Window Text"}}, "Progress bar": {
                       "terminado": {"Gradient 1": "#038738", "Gradient 2": "#87d77e", "Border": "#abd094"},
                       "renderizando": {"Gradient 1": "#355396", "Gradient 2": "#7DC1F2", "Border": "#82C5F4"},
                       "interrumpido": {"Gradient 1": "#C86000", "Gradient 2": "#FF912D", "Border": "#E3A746"},
                       "desactivado": {"Gradient 1": "#AAAAAA", "Gradient 2": "#AAAAAA", "Border": "#AAAAAA"}},
                    "iconos": {"enabled": "#000000", "disabled": "#a9a9a9"}},
               "Bee-renderon":
                   {"Main": {"10": {"color": "#242424", "nombre": "Window"},
                             "0": {"color": "#fffff6", "nombre": "Window Text"},
                             "9": {"color": "#a1a19b", "nombre": "Base"},
                             "16": {"color": "#878782", "nombre": "Alternate Base"},
                             "6": {"color": "#fffff6", "nombre": "Text"}, "1": {"color": "#362103", "nombre": "Button"},
                             "8": {"color": "#e59006", "nombre": "Button Text"},
                             "12": {"color": "#c3d9ff", "nombre": "Highlight"},
                             "13": {"color": "#0036ca", "nombre": "Highlighted Text"},
                             "998": {"color": "#5c7944", "nombre": "Checked watchfolders background"},
                             "999": {"color": "#A9FFFF", "nombre": "Checked scheduler background"},
                             "1000": {"color": "#FF0000", "nombre": "Checked shutdown background"}},
                    "Disabled": {"2": {"color": "#38de85", "nombre": "Disabled Light"},
                                 "6": {"color": "#5a6678", "nombre": "Disabled Text"},
                                 "8": {"color": "#707069", "nombre": "Disabled Button Text"},
                                 "0": {"color": "#86988d", "nombre": "Disabled Window Text"}}, "Progress bar": {
                       "terminado": {"Gradient 1": "#00a727", "Gradient 2": "#87d77e", "Border": "#abd094"},
                       "renderizando": {"Gradient 1": "#355396", "Gradient 2": "#7DC1F2", "Border": "#82C5F4"},
                       "interrumpido": {"Gradient 1": "#C86000", "Gradient 2": "#FF912D", "Border": "#E3A746"},
                       "desactivado": {"Gradient 1": "#AAAAAA", "Gradient 2": "#AAAAAA", "Border": "#AAAAAA"}},
                    "iconos": {"enabled": "#e59006", "disabled": "#a9a99f"}},

               "Morado": {"Main": {"10": {"color": "#4d0c5d", "nombre": "Window"},
                                   "0": {"color": "#D9D9D9", "nombre": "Window Text"},
                                   "9": {"color": "#524eb5", "nombre": "Base"},
                                   "16": {"color": "#20367f", "nombre": "Alternate Base"},
                                   "6": {"color": "#FCFCFC", "nombre": "Text"},
                                   "1": {"color": "#682147", "nombre": "Button"},
                                   "8": {"color": "#FFFFFF", "nombre": "Button Text"},
                                   "12": {"color": "#5680C2", "nombre": "Highlight"},
                                   "13": {"color": "#000000", "nombre": "Highlighted Text"},
                                   "998": {"color": "#e5c2c2", "nombre": "Checked watchfolders background"},
                                   "999": {"color": "#A9FFFF", "nombre": "Checked scheduler background"},
                                   "1000": {"color": "#FF0000", "nombre": "Checked shutdown background"}},
                          "Disabled": {"2": {"color": "#000000", "nombre": "Disabled Light"},
                                       "6": {"color": "#A9A9A9", "nombre": "Disabled Text"},
                                       "8": {"color": "#A9A9A9", "nombre": "Disabled Button Text"},
                                       "0": {"color": "#A9A9A9", "nombre": "Disabled Window Text"}}, "Progress bar": {
                       "terminado": {"Gradient 1": "#056C04", "Gradient 2": "#46D708", "Border": "#92D050"},
                       "renderizando": {"Gradient 1": "#355396", "Gradient 2": "#7DC1F2", "Border": "#82C5F4"},
                       "interrumpido": {"Gradient 1": "#C86000", "Gradient 2": "#FF912D", "Border": "#E3A746"}},
                          "iconos": {"enabled": "#ffb811", "disabled": "#55437c"}},
               "Reboton":
                   {"Main": {"10": {"color": "#9ec50f", "nombre": "Window"},
                             "0": {"color": "#D9D9D9", "nombre": "Window Text"},
                             "9": {"color": "#90d0cb", "nombre": "Base"},
                             "16": {"color": "#73a7a7", "nombre": "Alternate Base"},
                             "6": {"color": "#FCFCFC", "nombre": "Text"}, "1": {"color": "#29a3bc", "nombre": "Button"},
                             "8": {"color": "#FFFFFF", "nombre": "Button Text"},
                             "12": {"color": "#5680C2", "nombre": "Highlight"},
                             "13": {"color": "#000000", "nombre": "Highlighted Text"},
                             "998": {"color": "#e5c2c2", "nombre": "Checked watchfolders background"},
                             "999": {"color": "#A9FFFF", "nombre": "Checked scheduler background"},
                             "1000": {"color": "#FF0000", "nombre": "Checked shutdown background"}},
                    "Disabled": {"2": {"color": "#000000", "nombre": "Disabled Light"},
                                 "6": {"color": "#A9A9nombravA9", "nombre": "Disabled Text"},
                                 "8": {"color": "#767676", "nombre": "Disabled Button Text"},
                                 "0": {"color": "#A9A9A9", "nombre": "Disabled Window Text"}},
                    "Progress bar": {
                        "terminado": {"Gradient 1": "#056C04", "Gradient 2": "#46D708", "Border": "#92D050"},
                        "renderizando": {"Gradient 1": "#355396", "Gradient 2": "#7DC1F2", "Border": "#82C5F4"},
                        "interrumpido": {"Gradient 1": "#C86000", "Gradient 2": "#FF912D", "Border": "#E3A746"}},
                    "iconos": {"enabled": "#313066", "disabled": "#6c5f53"}}

               }
